Adds. non-browser-based test script
datopian/ckan-integration-tests pull request #8
Opened 2020-11-20 20:09 UTC by cuducos

This PR suggests a simple script to call CKAN JavaScript Client and create and push a blob to a resource using CKAN API. In the future, it can be moved to Cypress, but at the moment I am struggling to run async code inside Cypress runner, so this comes in as a _hot fix_ to be reverted soon.

2020-11-22 09:04 UTC, rufuspollock commented
@cuducos great and I assume you have run this and it works (?).

2020-11-22 09:07 UTC, rufuspollock requested changes
Small questions.

2020-11-22 09:07 UTC, rufuspollock commented on README.md
> +$ node ntegration_test_with_ckan_client.js <ORGANIZATION NAME>
is that a typo: "ntegration_test..."

2020-11-22 09:07 UTC, rufuspollock commented on README.md
> +This script requires a CKAN instance set with an organization.
What does this script do? I assume it auto creates a dataset, resource and then uploads file. Let's mention that and make sure his information it output by the script (e.g. urls are output to dataset and resource).

2020-11-24 17:46 UTC, cuducos commented
Thanks for the feedback. I think @cotts, @kmanaseryan and I can quickly work on #9 and #10, making this PR obsolete.Let's keep it open more 24h and we decide to close or merge this. Does that make sense?

2020-11-25 19:45 UTC, cuducos commented
Closed in favor of #13 (although documentation as described in #9 is still pending).

2020-11-25 19:45 UTC, closed without merging